/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20Token } from "./ERC20Token";
export type { PrivateERC20Token } from "./PrivateERC20Token";
