version: "3.9"

services:
  nginx:
    image: nginx:1.15-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/health.conf:/etc/nginx/health.conf
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - /var/www/pki-validation:/var/www/pki-validation
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    container_name: redis
    image: redis
    restart: on-failure
    ports:
      - "6379:6379"

  coti-transaction-app:
    container_name: coti-transaction-app
    build:
      context: ${BUILD_CONTEXT:-.}
    image: ${IMAGE_NAME:-coti-transaction-app:latest}
    volumes:
      - ${ENV_FILE:-./.env.coti-transactions}:/app/.env.coti-transactions
    ports:
      - ${PORT:-3000}:${DOCKER_PORT:-3000}
    extra_hosts:
      - "host.docker.internal:host-gateway"