/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC20Token__factory } from "./ERC20Token__factory";
export { PrivateERC20Token__factory } from "./PrivateERC20Token__factory";
