/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AccountOnboard__factory } from "./AccountOnboard__factory";
export { ERC20__factory } from "./ERC20__factory";
export { PrivateERC20__factory } from "./PrivateERC20__factory";
