export enum TableNames {
  USERS = 'users',
  OTPS = 'otps',
  OAUTH2_LOGINS = 'oauth2_logins',
  OAUTH2_LOGIN_PROFILES = 'oauth2_login_profiles',
  USER_WALLETS = 'user_wallets',
  ADDRESS_BOOKS = 'address_books',
  NETWORKS = 'networks',
  TOKENS = 'tokens',
  USER_WALLET_TOKENS = 'user_wallet_tokens',
  COTI_BLOCKS = 'coti_blocks',
  COTI_TRANSACTIONS = 'coti_transactions',
  COTI_LOGS = 'coti_logs',
  COTI_TOKENS = 'coti_tokens',
  COTI_ACTIVITIES = 'coti_activities',
  APP_STATES = 'app_states',
  AES_KEYS = 'aes_keys',
}
